import numpy as np

#create three array,the first two for store frequency and amplitude value
f = [200.0, 440.0, 500.0]
a = [0.5, 1.0, 2.0, 3.0]
array = []

#set samplingrate and duriation
srate = 44100.0
duration = 5

#define a sinusoid function
def generate_sin(freq, duration, srate, amp): 
    t = np.linspace(0,duration,int(srate*duration))
    data = amp * np.sin(2*np.pi*freq *t)
    return data

#storing the sinusiod value that generated by different frequency and amplitude
for freq in f:
    for amp in a:
        array.append(generate_sin(freq, duration, srate, amp))


data = np.hstack(array)

def peak_amplitude(data): 
    return np.max(data)
    
def rms_amplitude(data): 
    rms_sum = 0.0
    for i in range(0, len(data)): 
        rms_sum += (data[i] * data[i])
    rms_sum /= len(data)
    return np.sqrt(rms_sum) * np.sqrt(2.0)
    
print ('peak amlplitude: ' + str(peak_amplitude(data)))
print ('RMS amplitude: ' + str(rms_amplitude(data) ))
